campaigns/urls.py
from django.urls import path
from . import views
from .views import(
    NewsListView,
    NewsCreateView,
    NewsUpdateView,
    NewsDeleteView,
    CampaignsListView,
    CampaignsDetailView,
    CampaignsCreateView,
    CampaignsUpdateView,
    CampaignsDeleteView,
    BonusesCreateView,
    BonusesUpdateView,
    BonusesDeleteView,
    BonusPurchaseView,
    ImagesCreateView,
    ImagesUpdateView,
    ImagesDeleteView,
)

urlpatterns = [
    path('', NewsListView.as_view(), name='campaigns-home'),
    path('campaigns/', CampaignsListView.as_view(), name='campaigns-list'),
    path('campaigns/<int:pk>/', CampaignsDetailView.as_view(), name='campaigns-detail'),
    path('campaigns/new/', CampaignsCreateView.as_view(), name='campaigns-create'),
    path('campaigns/<int:pk>/update/', CampaignsUpdateView.as_view(), name='campaigns-update'),
    path('campaigns/<int:pk>/delete/', CampaignsDeleteView.as_view(), name='campaigns-delete'),
    path('campaigns/<int:pk>/bonuses/new', BonusesCreateView.as_view(), name='bonuses-create'),
    path('bonuses/<int:pk>/update', BonusesUpdateView.as_view(), name='bonuses-update'),
    path('bonuses/<int:pk>/delete', BonusesDeleteView.as_view(), name='bonuses-delete'),
    path('campaigns/<int:pk1>/bonuses/<int:pk2>/purchase', BonusPurchaseView, name='bonuses-purchase'),
    path('campaigns/<int:pk>/images/new', ImagesCreateView.as_view(), name='images-create'),
    path('images/<int:pk>/update', ImagesUpdateView.as_view(), name='images-update'),
    path('images/<int:pk>/delete', ImagesDeleteView.as_view(), name='images-delete'),
    path('campaigns/<int:pk>/news/new', NewsCreateView.as_view(), name='news-create'),
    path('news/<int:pk>/update', NewsUpdateView.as_view(), name='news-update'),
    path('news/<int:pk>/delete', NewsDeleteView.as_view(), name='news-delete'),
]

crowdfunding_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from users import views as user_views
# ***DRF***
from rest_framework import routers
from crowdfunding_project.api import views

# ***DRF***
router = routers.DefaultRouter()
router.register(r'campaigns', views.CampaignViewSet)
router.register(r'bonuses', views.BonusViewSet)
router.register(r'news', views.NewsViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('campaigns.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    # ***DRF***
    path('api/', include(router.urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campaigns/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# TODO: add tags model, add get_absolute_url, ADD COMMENTS

CAMPAIGN_THEME_CHOICES = (
    ('all', 'All'),
    ('education', 'Education'),
    ('electronics', 'Electronics'),
    ('entertainment', 'Entertainment'),
    ('sport', 'Sport'),
    ('IT', 'IT'),
)


class Campaign(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    theme = models.CharField(max_length=255, choices=CAMPAIGN_THEME_CHOICES, default='all')
    tags = models.CharField(max_length=255)
    video_URL = models.CharField(max_length=255)
    target_money = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=timezone.now)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('campaigns-detail', kwargs={'pk': self.pk})

    @property
    def get_video(self):
        url = str(self.video_URL)
        parts = url.split('watch?v=')
        try:
            return parts[0] + 'embed/' + parts[1] + '?rel=0'
        except Exception:
            return 'error'


def upload_gallery_image(instance, filename):  # change when the gallery is in the cloud
    return f"images/{instance.campaign.name}/gallery/{filename}"


class Bonus(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    description = models.TextField()
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE, related_name="bonuses")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('campaigns-detail', kwargs={'pk': self.campaign.pk})


class Image(models.Model):
    image = models.ImageField(upload_to=upload_gallery_image)
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE, related_name="images")

    def get_absolute_url(self):
        return reverse('campaigns-detail', kwargs={'pk': self.campaign.pk})


class News(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    image = models.ImageField(default='default.jpg', upload_to='news_pics')
    date_posted = models.DateTimeField(default=timezone.now)
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return '/'


class UserBonus(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bonus = models.ForeignKey(Bonus, on_delete=models.CASCADE)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #
    #     img = Image.open(self.image.path)
    #
    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from campaigns.models import UserBonus, Campaign


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been created. You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required()
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    bonuses = UserBonus.objects.filter(user=request.user)
    campaigns = Campaign.objects.filter(owner=request.user)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'bonuses': bonuses,
        'campaigns': campaigns,
    }
    return render(request, 'users/profile.html', context)

users/templates/users/login.html
{% extends "campaigns/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log in</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Log in</button>
                <small class="text-muted ml-2">
                    <a href="">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "campaigns/base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "campaigns/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        {% if user.campaign_set.count > 0 %}
          <h3 class="article-title">My Campaigns</h3>
          <div class="mb-3">
            {% for campaign in campaigns %}
              <div class="card mb-1">
                <div class="card-body">
                    <h5><a class="article-title" href="{% url 'campaigns-detail' campaign.id %}">{{ campaign.name }}</a></h5>
                    <div>
                    <a href="{% url 'news-create' campaign.id %}" class="btn btn-info btn-sm mt-1 mb-1">Post News</a>
                    <a href="{% url 'campaigns-update' campaign.id %}" class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
                    <a href="{% url 'campaigns-delete' campaign.id %}" class="btn btn-danger btn-sm mt-1 mb-1">Delete</a>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        {% endif %}
        {% if bonuses.count > 0 %}
          <h3 class="article-title">Purchased Bonuses</h3>
          <div class="mb-3">
            {% for item in bonuses %}
              <div class="card mb-1">
                <div class="card-body">
                  <h5><a class="article-title border-bottom pb-2" href="{% url 'campaigns-detail' item.bonus.campaign.id %}">{{ item.bonus.campaign.name }}</a></h5>
                  <h5 class="card-title pt-2">{{ item.bonus.name }}</h5>
                  <h6 class="card-subtitle mb-2 text-info">Price: {{ item.bonus.price }} c.u.</h6>
                  <p class="card-text">{{ item.bonus.description }}</p>
                </div>
              </div>
            {% endfor %}
          </div>
        {% endif %}
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
      </form>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "campaigns/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}